-- Enable Row Level Security (RLS) is recommended but we'll start open for simplicity
-- You can enable RLS later and add policies for authenticated users if needed.

-- 1. Task States Table
CREATE TABLE IF NOT EXISTS task_states (
    id BIGINT PRIMARY KEY, -- Corresponds to task index (0-30)
    current_index BIGINT DEFAULT 0,
    skips JSONB DEFAULT '[]'::jsonb,
    extras JSONB DEFAULT '[]'::jsonb,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Roster Settings Table
CREATE TABLE IF NOT EXISTS roster_settings (
    key TEXT PRIMARY KEY, -- e.g., 'custom_roster'
    value JSONB,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Task History Table
CREATE TABLE IF NOT EXISTS task_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_name TEXT NOT NULL,
    people JSONB NOT NULL, -- Array of names
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Roster History Table
CREATE TABLE IF NOT EXISTS roster_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    details TEXT NOT NULL,
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS (Optional, good practice)
ALTER TABLE task_states ENABLE ROW LEVEL SECURITY;
ALTER TABLE roster_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE task_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE roster_history ENABLE ROW LEVEL SECURITY;

-- Create policies to allow public read/write (since we don't have auth yet)
-- WARNING: This allows anyone with the anon key to read/write. 
-- For a lab tool on a private network or low stakes, this might be acceptable initially.
CREATE POLICY "Public read access" ON task_states FOR SELECT USING (true);
CREATE POLICY "Public write access" ON task_states FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update access" ON task_states FOR UPDATE USING (true);

CREATE POLICY "Public read access" ON roster_settings FOR SELECT USING (true);
CREATE POLICY "Public write access" ON roster_settings FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update access" ON roster_settings FOR UPDATE USING (true);

CREATE POLICY "Public read access" ON task_history FOR SELECT USING (true);
CREATE POLICY "Public write access" ON task_history FOR INSERT WITH CHECK (true);

CREATE POLICY "Public read access" ON roster_history FOR SELECT USING (true);
CREATE POLICY "Public write access" ON roster_history FOR INSERT WITH CHECK (true);
